### ISSUE TITLE
@Published property wrapper doesn't work

### ISSUE THREAD

**Issue by MaxDesiatov** [broadwaylamb/OpenCombine#102]
I see in project's release notes that `@Published` doesn't work yet, which is confusing as it's available in the list of public module declarations. In addition, the property is not recognized even when `import OpenCombine` is present in the file. Would be great to know if there are some specific reasons for that, otherwise, just creating an issue to track this. Maybe someone could provide more info or directions on the best way to fix this 🙏

**Comment by broadwaylamb** [comment]
Hi!

Are you also importing Foundation? If yes, this is a known issue: Foundation re-exports Published: 

```swift
public typealias Published = Combine.Published
```

This causes ambiguity, so you need to use `@OpenCombine.Published`.

I’m working on `Published` and `ObservableObject` in #97, and most of the work is done, expect it in the next minor update.
