### ISSUE TITLE
Missing `Future` publisher

### ISSUE THREAD

**Issue by MaxDesiatov** [broadwaylamb/OpenCombine#105]
I've tried to port [GRDBCombine](https://github.com/groue/GRDBCombine) to OpenCombine and it seems like the biggest missing piece there is a lack of the [`Future`](https://developer.apple.com/documentation/combine/future) publisher. Just adding it as a separate issue here for now to hopefully bump its priority on a possible OpenCombine roadmap 🙂

**Comment by royhsu** [comment]
@MaxDesiatov shouldn't Future defer `attemptToFulfill` until a subscriber calls `request(_:)`? I think Future type should be zero-cost abstraction since we don't know when library users will attach subscribers.

I have implemented my own version of Future type does that [here](https://github.com/royhsu/tiny-combine/blob/master/Sources/TinyCombine/Future.swift).

**Comment by broadwaylamb** [comment]
@royhsu good point, I think `attemptToFulfill` is marked `@escaping` for a reason.

Also, I just realized that even when the future has resolved, we shouldn’t send the result downstream until it requests at least one element. This is what’s already happening, but we don’t have a test case that tests this behavior.

**Comment by royhsu** [comment]
@broadwaylamb Yes, we should load data lazily as we can.

**Comment by broadwaylamb** [comment]
I've just checked. This code:

```swift
let future = Future<Int, Never> { _ in
    print("called!")
}
```

unconditionally prints "called!" when using Combine. So it seems what @royhsu proposes is **not** how Combine handles it.

But it's totally worth adding a test. @MaxDesiatov can you do it?

To sum up, we need tests that:

- ensure `attemptToFulfill` is always called immediately;
- ensure that the value is not sent downstream even when the future has resolved, until the downstream requests at least one element.

**Comment by royhsu** [comment]
I just posted the question to Swift Forum. Hope there is someone can explain why they decide to do that.

[Why does Future type need to call attempToFulfill immediately in Combine?](https://forums.swift.org/t/why-does-future-type-need-to-call-attemptofulfill-immediately-in-combine/31130)

**Comment by MaxDesiatov** [comment]
This is a standard behaviour of most popular future libraries, e.g. [BrightFutures](https://github.com/Thomvis/BrightFutures) and [PromiseKit](https://github.com/mxcl/PromiseKit). The benefit is that you don't have to manually retain the future for it to execute, it will either execute immediately or will be retained by a queue it's currently scheduled on. And I do quite like the fact that Combine follows this behavior, this way it's so much easier to migrate from any of those libraries to Combine/OpenCombine.

Besides, you can always wrap your `Future` with [`Deferred`](https://developer.apple.com/documentation/combine/deferred) if needed.

I'll add the tests in a separate PR 👍

**Comment by royhsu** [comment]
@MaxDesiatov Cool, now I got it. Would you mind to reply the answer on the Forum too?
