### ISSUE TITLE
DropWhile doesn't need `Predicate` generic constraint on class

### ISSUE THREAD

**Issue by spadafiva** [broadwaylamb/OpenCombine#11]
Does DropWhile need to have `Predicate` in the `_DropWhile` generic specialization?  It isn't referenced anywhere in the body of the class and when I removed it everything continued to pass tests.

**Comment by broadwaylamb** [comment]
I used some reverse engineering when implemented `DropWhile` and saw that Apple's Combine used `Predicate` as a generic parameter for some reason. As of Xcode 11.0 beta 2 AFAICT this is no longer the case.

Addressed in #14.
