### ISSUE TITLE
URLSession.dataTaskPublisher for OpenCombine?

### ISSUE THREAD

**Issue by doronkatz** [broadwaylamb/OpenCombine#124]
Hi there

So I am on the home stretch, but I have a few issues. Firstly:
I am getting 
```
error: value of type 'URLSession' has no member 'dataTaskPublisher'
            self.urlSession.dataTaskPublisher(for: request)
```

Is there an OpenCombine equivalent to use `dataTaskPublisher`?

Secondly, I am also getting:
```
error: value of type 'Any' has no member 'tryMap'
                .tryMap { (data, response) -> Data in
```
Is this also functional in OpenCombine?

Thanks once again 🙏🏻

**Comment by MaxDesiatov** [comment]
Hi @doronkatz, none of `Foundation` extensions that Combine provides are in OpenCombine yet. As for the second error, it seems like a type inference issue, most probably caused by `dataTaskPublisher` not available in current scope, thus the compiler is not able to figure out in which namespace `.tryMap` is invoked.

**Comment by doronkatz** [comment]
Oh thanks @MaxDesiatov. I see... Yeah may have to wait or help contribute to get that across.. As for the second issue, it only happens on Unix and not on iOS/macOS. So that's why i wasn't sure about the context..

**Comment by broadwaylamb** [comment]
@doronkatz hi! I’ll get to URLSession as soon as #84 is ready, since it lays the groundwork for supporting Foundation extensions.

It should be pretty soon!

**Comment by doronkatz** [comment]
Awesome excellent work :)

**Comment by broadwaylamb** [comment]
The functionality is available in master.

Note that on Darwin platforms, you'll need to use the `ocombine` property to disambiguate (since Foundation extends `URLSession` with a method with the same name):

```swift
let publisher = self.urlSession.ocombine.dataTaskPublisher(for: request)
```

On Linux, you can omit this.

**Comment by doronkatz** [comment]
Thanks @broadwaylamb. Silly question but how do you test if its linux? I was looking at `#if canImport(Combine) ....` but don't think that works for this

**Comment by broadwaylamb** [comment]
We don’t need to test if it’s Linux. The ambiguity takes place only if Combine is present on your platform, so `#if canImport(Combine)` should be enough.

**Comment by doronkatz** [comment]
Right, so when i run it on my macOS it works fine, but when i build it in Docker Unix:
```
/app/Sources/SwiftRecommendations/Services/APIService.swift:62:45: error: value of type 'URLSession' has no member 'ocombine'
            let publisher = self.urlSession.ocombine.dataTaskPublisher(for: request)
```

My code changes are:
```
#if canImport(Combine)
            let publisher = self.urlSession.dataTaskPublisher(for: request)
            #else
            let publisher = self.urlSession.ocombine.dataTaskPublisher(for: request)
            #endif
```

**Comment by MaxDesiatov** [comment]
Did you build from latest `master` and added `import OpenCombine` to `APIService.swift`?

**Comment by MaxDesiatov** [comment]
Probably requires `import OpenCombineFoundation` as well.

**Comment by doronkatz** [comment]
I didn't try the last one, but it can't find `OpenCombineFoundation`. I have the latest (master) and have imported `OpenCombine`. 

My package:
```
.package(url: "https://github.com/broadwaylamb/OpenCombine.git",
                 .branch("master"))
```

**Comment by MaxDesiatov** [comment]
Thanks for reporting this, I've created #124, which should fix this.

**Comment by doronkatz** [comment]
Thanks I’ll track that 


This email and any attachments are confidential and may be subject to copyright, legal or some other professional privilege.
They are intended solely for the attention and use of the named addressee(s). They may only be copied, distributed or
disclosed with the consent of the copyright owner. If you have received this email by mistake or by breach of the confidentiality
clause, please notify the sender immediately by return email and delete or destroy all copies of the email. Any confidentiality,
privilege or copyright is not waived or lost because this email has been sent to you by mistake.

**Comment by broadwaylamb** [comment]
> Right, so when i run it on my macOS it works fine, but when i build it in Docker Unix:
> 
> ```
> /app/Sources/SwiftRecommendations/Services/APIService.swift:62:45: error: value of type 'URLSession' has no member 'ocombine'
>             let publisher = self.urlSession.ocombine.dataTaskPublisher(for: request)
> ```
> 
> My code changes are:
> 
> ```
> #if canImport(Combine)
>             let publisher = self.urlSession.dataTaskPublisher(for: request)
>             #else
>             let publisher = self.urlSession.ocombine.dataTaskPublisher(for: request)
>             #endif
> ```

You don’t have to write this condition. `ocombine` is available on Linux too. Basically, if you want to use OpenCombine on Linux, and leverage Combine on macOS, you use `self.urlSession.dataTaskPublisher(for: request)`. If you want to just use OpenCombine everywhere, use `self.urlSession.ocombine.dataTaskPublisher(for: request)`.

**Comment by doronkatz** [comment]
@broadwaylamb so if I use just `urlSession.dataTaskPublisher...` I get on Unix:
```
error: value of type 'URLSession' has no member 'dataTaskPublisher'
            let publisher = self.urlSession.dataTaskPublisher(for: request)
```

So not sure if it is the case pr i am doing something else... I do want to use OCombine for Unix and Combine for Darwin ideally

**Comment by broadwaylamb** [comment]
Are you also importing the OpenCombineFoundation module? Because it is required in order to use URLSession extensions.

**Comment by doronkatz** [comment]
Yeah so that part I think there is a fix for (another issue) right, as it didn’t allow me to (from previous comments).

**Comment by broadwaylamb** [comment]
Yes, if you upgrade to the latest master and import OpenCombineFoundation, everything should work.

**Comment by doronkatz** [comment]
Thanks @broadwaylamb  I think I had a cache issue. I re-did the imports and added the targets and it works now perfectly... `OpenCombineFoundation` is my savior across both platforms.

Thanks!
