### ISSUE TITLE
OpenCombine organization?

### ISSUE THREAD

**Issue by MaxDesiatov** [broadwaylamb/OpenCombine#125]
I'm currently maintaining a few forks of open-source libraries that make those compatible with OpenCombine: [GRDBOpenCombine](https://github.com/MaxDesiatov/GRDBOpenCombine) and its dependency [OpenCombineExpectations](https://github.com/MaxDesiatov/OpenCombineExpectations). I'd appreciate any input and contributions to these forks, and maybe some coordinated effort to push a more sane support for "polyfill" libraries in future versions of Swift. If the latter happens, we probably even could upstream changes from these forks to their origin repositories.

Either way, it would make sense to maintain these forks, proposals, and related helper projects under one umbrella OpenCombine organization with an open list of maintainers. This would make the project more visible and I hope attract more attention and contributors. I'm not sure if existing [OpenCombine](https://github.com/opencombine) organization is the one previously created for this purpose, if not maybe something like OpenCombineHQ could work as a name just as well.

**Comment by broadwaylamb** [comment]
Good idea! Yep, I created that organization exactly for this purpose.

**Comment by broadwaylamb** [comment]
@MaxDesiatov do you want me to do anything regarding this issue?

**Comment by MaxDesiatov** [comment]
I was just wondering whether you have any plans with regards to the organization, are you going to transfer the repository to it?

**Comment by broadwaylamb** [comment]
I guess I am.

**Comment by MaxDesiatov** [comment]
Awesome!

**Comment by broadwaylamb** [comment]
Huh. CircleCI has stopped working because of the transfer. I've contacted their support, let's wait what they say.

**Comment by MaxDesiatov** [comment]
Yeah, I had a similar issue with Codecov when I was transferring my repos to an org, the repo never showed up there under the new org, so I couldn't get a new Codecov token. The only thing that helped me with Codecov was logging out, clearing all cokies and logging in again. Not sure if it's the same thing with Circle CI though.

**Comment by broadwaylamb** [comment]
The thing with CircleCI is that I've been using a free plan for macOS builds, which can only be obtained by writing to their support. The Linux builds are fine.

**Comment by MaxDesiatov** [comment]
GitHub Actions supports Xcode 10.3 on macOS, so just in case CircleCI is not fixed, I hope you would consider GHA. GHA also seems much faster as it allows some parallelism for open-source repositories.

**Comment by broadwaylamb** [comment]
AFAICT GitHub Actions only support macOS Catalina. For testing on iOS 9.3 (and 32 bits) we have to use macOS Mojave, because on Catalina Xcode doesn't allow us to download iOS simulators that old.

I'd be happy to use GHA, but I'm not ready to give that up.

**Comment by MaxDesiatov** [comment]
Mojave is also supported on Azure Pipelines, just in case.

**Comment by broadwaylamb** [comment]
The CI’s up and running again, folks at CircleCI were very helpful.
