### ISSUE TITLE
Combine documentation states that the Subscription protocol is class constrained

### ISSUE THREAD

**Issue by vukrado** [broadwaylamb/OpenCombine#152]
Im not sure if this is an issue in Apples documentation or implementation but according to the [documentation](https://developer.apple.com/documentation/combine/subscription) it says "Subscriptions are class constrained because a Subscription has identity, defined by the moment in time a particular subscriber attached to a publisher." But according to the implementation it is not class constrained. I see two instances of a non class conformance to Subscription in OpenCombine one is `SideEffectSubscription` in `Publishers.Autoconnect` and the other is `_EmptySubscription`. I am not sure if I am missing something here but I was wondering what everyones thoughts are on this

**Comment by broadwaylamb** [comment]
Yeah, well, much of the documentation on Combine is misleading or just wrong. Like with [multicast](https://developer.apple.com/documentation/combine/publisher/3204733-multicast), where it says:

>In contrast with `multicast(subject:)`, this method produces a publisher that creates a separate Subject for each subscriber.

`Subscription` is not class-constrained in Combine as well.
