### ISSUE TITLE
consider adapting Apple's implementations of Foundation and Dispatch publishers

### ISSUE THREAD

**Issue by mayoff** [broadwaylamb/OpenCombine#153]
Apple's implementations of the Foundation and Dispatch publishers and schedulers are part of the Swift open-source project. Have you considered adapting those implementations for OpenCombine?

Here are the files of interest:

- [`Publishers+KeyValueObserving.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BKeyValueObserving.swift)
- [`Publishers+Locking.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BLocking.swift)
- [`Publishers+NotificationCenter.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BNotificationCenter.swift)
- [`Publishers+Timer.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BTimer.swift)
- [`Publishers+URLSession.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BURLSession.swift)
- [`Schedulers+Date.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Schedulers%2BDate.swift)
- [`Schedulers+OperationQueue.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Schedulers%2BOperationQueue.swift)
- [`Schedulers+RunLoop.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Schedulers%2BRunLoop.swift)
- [`Schedulers+DispatchQueue.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Dispatch/Schedulers%2BDispatchQueue.swift)

**Comment by broadwaylamb** [comment]
Nice! I'll do it.

**Comment by broadwaylamb** [comment]
The implementations of all those entities are in the main branch. They're based on Apple's, but tweaked to work with the platforms and language versions that we support.

The only exception is `Publishers+KeyValueObserving.swift`. There are certain issues with it. If anyone feels they should be prioritized, please create a new issue.
