### ISSUE TITLE
[Question] Reason behind Publisher.makeConnectable’s Failure constraint

### ISSUE THREAD

**Issue by jasdev** [broadwaylamb/OpenCombine#154]
Not an “issue” per se but, a question (also [mirrored on the Swift forums](https://forums.swift.org/t/getting-an-intuition-around-publisher-makeconnectable/36055)). Do you know why Combine fences off `Publisher.makeConnectable` for when `Failure == Never`? Seems like the project still compiles without it, so I’m having trouble building an intuition for why it’s needed.

https://github.com/broadwaylamb/OpenCombine/blob/d680f09932fe68942c3d391d6df296d38b9dcd05/Sources/OpenCombine/Publishers/Publishers.MakeConnectable.swift#L8

Did you end up leaning on that `Never` constraint when writing OpenCombine?

**Comment by broadwaylamb** [comment]
Hi!

Nope, I don’t know why this decision was made, and I find it weird too.

**Comment by jasdev** [comment]
Phew, glad I wasn’t the only one who scratched my head at this. 😄 Cheers!
