### ISSUE TITLE
Question: Synthetize ObjectWillChange for @Published

### ISSUE THREAD

**Issue by nidegen** [broadwaylamb/OpenCombine#160]
Does OpenCombine manage automatic @Published linking to ObservableObject?

I tried to find any hints in the code, but there seem not to be any explicit code.

For Combine, they use something as described in this thread:
https://twitter.com/luka_bernardi/status/1155944329363349504?s=20

**Comment by nidegen** [comment]
ah, found some talk on #97. Seems like an unsolved issue then?

**Comment by nidegen** [comment]
Would there be a way to add `subscript<EnclosingSelf: ObservableObject>` only for ObservableObjects? A conditional extension on Published where EnclosingSelf conforms to ObservableObject? Guess that is impossible now

**Comment by maximkrouk** [comment]
Maybe a custom property will work?

```swift
@propertyWrapper
struct OCombinePublished<Value> {
  public static subscript<EnclosingSelf: ObservableObject>(
    _enclosingInstance instance: EnclosingSelf,
    wrapped wrappedKeyPath: ReferenceWritableKeyPath<EnclosingSelf, Value>,
    storage storageKeyPath: ReferenceWritableKeyPath<EnclosingSelf, Self>
  ) -> Value where EnclosingSelf.ObjectWillChangePublisher {
    get { instance[keyPath: storageKeyPath].value }
    set {
      instance[keyPath: storageKeyPath].value = newValue
      instance.objectWillChange.send()
    }
  }
  
  var value: Value
  
  /// See ``Dependency`` discussion
  public init(wrappedValue: Value) {
    self.value = wrappedValue
  }
  
  public var wrappedValue: Value {
    get { value }
    set { value = newValue }
  }
}
```
