### ISSUE TITLE
Can not import @Published directly

### ISSUE THREAD

**Issue by albertopeam** [broadwaylamb/OpenCombine#184]
I am not able to use directly `@Published`, instead I had to use `@OpenCombine.Published`. Is there any way to make it work?
I have pushed a demo to a [repository](https://github.com/albertopeam/swift/blob/master/OpenCombineUsage/OpenCombineUsage/AppDelegate.swift)
PD: iOS11 target

Great work with the open source library. Thanks :)

**Comment by broadwaylamb** [comment]
The only way to make it work is to add the following line to your code:

```swift
typealias Published = OpenCombine.Published
```

This type alias will shadow all the types named `Published` defined in other modules.

This is a language limitation, so, unfortunately, we can't fix it in OpenCombine.
