### ISSUE TITLE
Build failing on iOS14

### ISSUE THREAD

**Issue by albertopeam** [broadwaylamb/OpenCombine#192]
Hi, I am trying to compile on iOS14 but it is failing. 

`testAssignToPublished` is using [assign(to: Publisher)](https://developer.apple.com/documentation/combine/publisher/assign(to:)) and the test case is wrapped with `@available(macOS 10.15, iOS 13.0, *)`, so when trying to make it compile it returns an error `'assign(to:)' is only available in iOS 14.0 or newer`. If we update the test case to use iOS14 it works, but I don't know if you are going to update this or split the tests between iOS13 and iOS14.

Environment: XCode12.1 + iOS14.1

Thank you.

**Comment by broadwaylamb** [comment]
Hi.

Could you please describe your setup in more details? Starting from cloning OpenCombine, what are the steps that lead to the issue?

**Comment by albertopeam** [comment]
Hi

Steps to reproduce:

1. Clone
2. Open in XCode12.1
3. Select `OpenCombine-Package` scheme
4. Add flag to test with Combine `.unsafeFlags(["-DOPENCOMBINE_COMPATIBILITY_TEST"])`in OpenCombineTests testTarget
```
.testTarget(
          name: "OpenCombineTests",
          dependencies: [
            "OpenCombine",
            .target(name: "OpenCombineDispatch", condition: .when(platforms: [.macOS, .iOS, .watchOS, .tvOS, .linux])),
            .target(name: "OpenCombineFoundation", condition: .when(platforms: [.macOS, .iOS, .watchOS, .tvOS, .linux])),
          ],
          swiftSettings: [
            .unsafeFlags(["-enable-testing"]),
            .unsafeFlags(["-DOPENCOMBINE_COMPATIBILITY_TEST"]),
            .define("WASI", .when(platforms: [.wasi]))
          ]
        )
```
5. Run tests for iOS14.1, it results in 11 errors in test target. 
6. ie: `testAssignToPublished` is failing due to `'assign(to:)' is only available in iOS 14.0 or newer`

Could you take a look? Maybe we understood something wrong.
Thank you for your support

Regards

**Comment by broadwaylamb** [comment]
Just FYI: you don't have to edit `Package.swift`. If you want to run compatibility tests on iOS, you can just run `make generate-compatibility-xcodeproj`. This will generate and open an Xcode project with the `OPENCOMBINE_COMPATIBILITY_TEST` flag set. After that you can just run the tests from Xcode.

Thanks for reporting the issue!

**Comment by albertopeam** [comment]
Thanks and apologies for creating issues with this kind of stuff.

I will take a look to `make generate-compatibility-xcodeproj`
