### ISSUE TITLE
OpenCombine/Combine discrepancy: Old values received by nested subscribers of @Published

### ISSUE THREAD

**Issue by uberbruns** [broadwaylamb/OpenCombine#198]
Consider the following code:

```
import Foundation

import Combine
//import OpenCombine
//typealias Published = OpenCombine.Published

class SomeDependency {
    @Published var value = 0
}

class NestedObject {
    let dependency: SomeDependency
    var subscriptions = Set<AnyCancellable>()

    init(dependency: SomeDependency) {
        self.dependency = dependency

        dependency.$value
            .sink { value in
                print("Nested:", value)
            }
            .store(in: &subscriptions)

    }
}

class SuperObject {
    let dependency: SomeDependency
    var nestedObject: NestedObject?
    var subscriptions = Set<AnyCancellable>()

    init(dependency: SomeDependency) {
        self.dependency = dependency

        dependency.$value
            .sink { [unowned self] value in
                print("Super:", value)
                if value == 1 {
                    nestedObject = NestedObject(dependency: dependency)
                }
            }
            .store(in: &subscriptions)
    }
}

let dependency = SomeDependency()
let superObject = SuperObject(dependency: dependency)
dependency.value = 1
```

When importing Apple's Combine the output for the _nested_ `print` is `1`. When importing OpenCombine the received value is `0`.

Kind regards

Karsten

**Comment by broadwaylamb** [comment]
Can I ask you on which OS version you're running it against Combine?

**Comment by broadwaylamb** [comment]
I've just run your test on iOS 14.2 (the newest one), the behavior is the same with both Combine implementations. Printing 0 makes more sense, since `Published` publishes values **before** they're actually set. I assume it was just a bug in Combine that has been fixed in more recent versions.

Nonetheless, thank you for the time you've spent for creating the test case and reporting this.

**Comment by uberbruns** [comment]
Its 10.15.7 Catalina … I'll see if I can reproduce it on other Versions.

**Comment by uberbruns** [comment]
You're right. Behaviour of Apples Combines is different here between OS Versions:

<img width="2092" alt="image" src="https://user-images.githubusercontent.com/981579/101141174-34528080-3614-11eb-9dc1-4432caf4d55e.png">
