### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by spadafiva** [broadwaylamb/OpenCombine#2]
I would like to be able to use combine in my projects that are pre-ios 13.  What do you need help with and how can I contribute?

**Comment by broadwaylamb** [comment]
@spadafiva that would be awesome! Feel free to take a look at #1 and pick any operator you’d like to implement. In that case don’t forget to comment on that issue that you’re working on it, so that we don’t end up doing the work twice :)

**Comment by broadwaylamb** [comment]
You might want to take a look at how `DropWhile` and `Sink` are already implemented in OpenCombine.

For now I haven’t been optimizing much, the number one goal is correctness and semantic compatibility with Apple’s Combine, i. e. the order in which functions are called, how demand is managed and so on. Hence unit tests are important.

**Comment by spadafiva** [comment]
@broadwaylamb

Thanks.  I'll probably start taking a look soon.

**Comment by spadafiva** [comment]
@broadwaylamb Hey, I just forked the repo and was going to take a look.  It looks like in the docs that all the different publishers have some shared instance methods.  I'm looking at your Drop implementations and was thinking about tackling the encode/decode ones next.  

Is your plan to implement all the operators and then write extensions on Publisher to handle the instance methods on all the operators?

**Comment by spadafiva** [comment]
@broadwaylamb Okay, just took another look.  I see how you added the extensions at the bottom of the file with the publisher.  That makes sense to me.

**Comment by spadafiva** [comment]
@broadwaylamb Okay, sorry to send you so many messages, but I wanted to see if I was going down the right path for what you'd like to see for this repo before I got too deep into this.  I've got an initial pass at the Decode publisher.  When I try to run the benchmarks, I'm getting a `signal code 11` exit.  I also haven't added all the comments / styling / etc, so I'd like to get your input on those things too.  Here's the link: https://github.com/spadafiva/OpenCombine/commit/c30298bd5a73886f2bb52be381376cb9eb71092a

**Comment by broadwaylamb** [comment]
Thank you @spadafiva! Looks like you’ve got it mostly right. Maybe it would be better if you could open a draft PR so it’s easier to leave comments.

I also should probably add SwiftLint support, but the general rule is: the line length is 90 characters, no white space before colons in inheritance clause.

>When I try to run the benchmarks, I'm getting a signal code 11 exit.

Is that a compiler crash or a runtime crash? How to reproduce it?

**Comment by spadafiva** [comment]
Thanks @broadwaylamb,

I'm getting it as a message when running the test suite from the command line.  I'm on my mobile right now, but it's using the command from your README.

I'll open an actual PR later once I get a chance today.

**Comment by M0rtyMerr** [comment]
Hey @broadwaylamb thank you for your great work.

I just wanted to note, that u should migrate from one letter generic names ASAP. I understand that u just follows Apple code style, but `S` for both `Subscriber` and `Subscription` is kinda bad choice.  A few months ago RxSwift removed all one-character generics from their repo, cause it was a real pain in the ass use `O` for `Observer` and `Observable`

What do you think? :)

**Comment by broadwaylamb** [comment]
@MortyMerr good idea!

**Comment by M0rtyMerr** [comment]
@broadwaylamb than we should rename `Subscriber` to `SubscriberType` and `S` to `Subscriber`. For instance:
```swift
private final class Inner<Subscriber: SubscriberType>:
```
What do you think?

**Comment by spadafiva** [comment]
@broadwaylamb Thanks for adding the new project file.  I think we should probably make an issue or some tracker for each remaining operator so that we can see what everyone is working on.

**Comment by broadwaylamb** [comment]
@MortyMerr that'd be incompatible with Apple's Combine, so no. Instead, we can do the other way around.

**Comment by broadwaylamb** [comment]
@spadafiva yep, that makes sense. I'm gonna do that tomorrow.

**Comment by M0rtyMerr** [comment]
@broadwaylamb I see your latest changes. Great work. But
```swift
public func receive<SubscriberType: Subscriber>
```
looks really strange. `SubscriberType` is something generic. `Subscriber` is a concrete type. You invert these type names and I think this can be unclear for a potential contributor. 
`SubscriberType` is something more general than `Subscriber`
We don't usually use `<Shape: Rectangle>` right?
What do u think?

**Comment by M0rtyMerr** [comment]
```swift
public func receive<_Subscriber: Subscriber>
```
might be better. What do you think?

**Comment by broadwaylamb** [comment]
@MortyMerr I don't like the leading underscore.

`Upstream`/`Downstream` is already used in some places, maybe we could use them instead.

**Comment by gokselkoksal** [comment]
Great work. I was going to start this myself if I haven't seen this. I can probably start helping out when I'm back from holidays.

I cloned the repo but don't see a xcodeproj/xcworkspace, that should probably be included in master so it's easier to work on. Is there a contribution guide?

**Comment by broadwaylamb** [comment]
@gokselkoksal thanks!

I intentionally don’t check in an xcodeproj for consistency with the Package.swift manifest. If you’re using Xcode 10, you can execute the following command in the terminal:

```
swift package generate-xcodeproj
```

and then open the generated project.

If you’re using Xcode 11, you can just open Package.swift and the workspace will open automatically with all the files and schemes.

**Comment by gokselkoksal** [comment]
OK that worked fine 👍 I'll check the board before picking up a task!
