### ISSUE TITLE
Should change unfair lock to unfair recursive lock in Sink?

### ISSUE THREAD

**Issue by James-Chi-Jie** [broadwaylamb/OpenCombine#208]
when AnyCancellable calls cancel function automatically in DEINIT, Sink's cancel function will be called, then terminateAndConsumeLock will be called. As the result, the receiveValue block and receiveCompletion block will be set to nil. Then objects in receiveValue block or receiveCompletion block may be destroyed. If there is an object that in block, it will call same sink's receive completion to finish in object's DEINIT function. That will make a crash cause call lock's lock function twice without unlock.

**Comment by broadwaylamb** [comment]
Do you have a code snippet that triggers the crash?

**Comment by James-Chi-Jie** [comment]
https://github.com/ArthurChi/OpenCombineDemo

**Comment by broadwaylamb** [comment]
@ArthurChi thank you for taking the time to report this bug! I've fixed it and will prepare a new release shortly.

**Comment by James-Chi-Jie** [comment]
I notice the MR's checks of this bug is failed, I submitted a MR to this branch to fix it

**Comment by James-Chi-Jie** [comment]
@broadwaylamb Could you please release a new version this week?
