### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by wangjiejacques** [broadwaylamb/OpenCombine#215]
Hi, what's the status of this framework, is it stable enough for production usage?

**Comment by broadwaylamb** [comment]
Some companies do use it in production.
It is pretty stable and the test coverage is extensive.

**Comment by maximkrouk** [comment]
It missing some functionality, but I think it's one of the most tested frameworks I've seen, I'm not sure that even the original Combine is tested that well, so if you don't need it's missing parts, I believe OpenCombine is currently the best FRP framework available 😎

**Comment by wangjiejacques** [comment]
Good to know, thanks.
