### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JQHxx** [broadwaylamb/OpenCombine#232]
![image](https://user-images.githubusercontent.com/16495357/161364006-668fc40c-d216-49ea-ab96-54b0538ca863.png)

**Comment by broadwaylamb** [comment]
Hi. Thank you for the report. Which version of Xcode are you using?

**Comment by JQHxx** [comment]
Xcode 13

**Comment by MaxDesiatov** [comment]
@JQHxx could you be more specific please? Is this Xcode 13.0, or 13.2? What's the full version number together with minor and patch components?

**Comment by JQHxx** [comment]
Xcode 13.0 Version 13.0 (13A233)     
pod 'OpenCombine', '~> 0.13.0'

**Comment by MaxDesiatov** [comment]
That's the reason for the error message. You'll have to use a version of Xcode that supports concurrency back-deployment when targeting iOS 14 or iOS 13, that is Xcode 13.2 or later. Latest version (which is 13.3 at the time of writing this) is recommended.
