### ISSUE TITLE
Add primary associated type support

### ISSUE THREAD

**Issue by Kyle-Ye** [broadwaylamb/OpenCombine#237]
When Swift released 5.7 in Xcode 14.0, Combine framework has updated its protocol interface to support primary associated type support.

eg.
```swift
// Latest Combine
public protocol Publisher<Output, Failure>
```
```swift
// Current OpenCombine and old Combine(iOS 15-)
public protocol Publisher
```

Adding such feature support enable us to use `some Publisher<Int, Error>` without needing to convert it to AnyPublisher.

```swift
func loadUser(
    withID id: User.ID
) -> some Publisher<User, Error> {
    urlSession
        .dataTaskPublisher(for: urlForLoadingUser(withID: id))
        .map(\.data)
        .decode(type: User.self, decoder: decoder)
}
```

See more info at [Combining opaque return types with primary associated types](https://www.swiftbysundell.com/articles/opaque-return-types-primary-associated-types)

**Comment by broadwaylamb** [comment]
It's implemented in #236. I'll merge it as soon as I fix the failing compatibility tests.
