### ISSUE TITLE
Tests don't compile with OPENCOMBINE_COMPATIBILITY_TEST enabled

### ISSUE THREAD

**Issue by ilijapuaca** [broadwaylamb/OpenCombine#35]
I picked up a few operators and thought I finished implementing them. I'm having a hard time verifying whether tests are ok since some files don't compile (tried Xcode 11 beta 1 and 4, the latest one).

The issues are mainly with a few Publishers that seem to be gone in the latest version of the framework, like Once and Empty. I guess I could just remove some of these from my test target, but I was wondering whether it's only me running into this issue?

Also, how should this be handled in general, I assume we'll have to revisit the API another few times (hopefully not that many since release is coming close), any plans on how to approach updating the API across the board?

**Comment by broadwaylamb** [comment]
Thanks for reporting this @ilijapuaca!

I’ve updated the project for beta 4 in #36, but it needs some minor cleanup before merging, I’ll get to it in today or tomorrow.
