### ISSUE TITLE
How to run compatibility test on macOS 10.14.

### ISSUE THREAD

**Issue by luoxiu** [broadwaylamb/OpenCombine#4]
Hi, @broadwaylamb !

First of all, great job! I came up with the same idea two days after the release of the Combine: using the power of the community to implement the official spec, making it no longer have the limitations of the os version and platform.

Actually, I've been working there for a few days, 😄:
<img width="954" alt="st" src="https://user-images.githubusercontent.com/18638838/59604115-c83d3d80-913d-11e9-81df-a48a679a73bc.png">

But I'm happy to see you have gone a step further than me, so I decided to stop my side and work with you to accomplish this goal together!

Before I make my first commit, I want to know, how to run a compatibility test on macOS 10.14?

**Comment by broadwaylamb** [comment]
Hello @luoxiu! I'm really happy to hear that!

As far as I can tell, it's not possible, since Apple's Combine is not available on macOS 10.14. I've been developing on macOS 10.15 beta.

**Comment by luoxiu** [comment]
It's not friendly to new contributors I think, macOS 10.15 beta is still a little bit buggy now.

My project is using the unit test target of an iOS app project for testing. It has two schemes: `Specs` and `CombineSpecs`, and they share the same test files, so you can write tests like:

```swift
#if CombineX
import CombineX
#else
import Combine
#endif
```

All you need is just Xcode beta, what do you think?

**Comment by broadwaylamb** [comment]
@luoxiu that's how it's implemented now in OpenCombine too. If that works on macOS 10.14, I'm glad to be mistaken.

For running compatibility tests I use the command line:
```
$ swift test -Xswiftc -DOPENCOMBINE_COMPATIBILITY_TEST
```

Let me know if you have any troubles.

**Comment by luoxiu** [comment]
No, I mean, `Xcode 11 beta` on `macOS 10.14` can run `iOS 13 beta` on the simulator. So developers don't need `macOS 10.15 beta` anymore!

Sorry for my broken English, 😄

**Comment by broadwaylamb** [comment]
@luoxiu have you managed to run the compatibility tests on iOS? If so, I think I should add support for compatibility testing on Travis CI (it's not enabled now as Travis doesn't have macOS 10.15 images yet).

**Comment by luoxiu** [comment]
I have not tested on Travis, they don't have Xcode beta either.

**Comment by broadwaylamb** [comment]
Oh, right.
