### ISSUE TITLE
Create removeDuplicates and removeDuplicates(by:)

### ISSUE THREAD

**Issue by jdisho** [broadwaylamb/OpenCombine#42]
Thank you for OpenCombine! 😊

I realised that the work for `removeDuplicates` and `removeDuplicates(by:)` is missing, so I am volunteering to work on these two operators. 

If that is fine to you @broadwaylamb, can you assign this issue to me? As far as I can see, I can not do it.

**Comment by broadwaylamb** [comment]
Thank you @jdisho!

I thought @FranzBusch wanted to implement those operators, so he mentioned on [our Slack channel](https://join.slack.com/t/opencombine/shared_invite/enQtNzE2MjE5NzkxODI0LTYxMjkzNDUxZWViZWI1Njc2YjBhODgxNjRjOTdkZTcxOGU2ZjJjZjYxMGI3NWZkN2RkNGFmZTUzNmU3MGE2ZWM).

**Comment by FranzBusch** [comment]
Yes, I have already something working quite nicely just need to implement more tests. I hope I can open a PR this weekend

**Comment by jdisho** [comment]
Okay! Does it make sense to you @broadwaylamb to update #1 regarding who-is-working-on-what? I assume you have a better overview about this. 😊
