### ISSUE TITLE
Why enforce matching of name of Subscription with Apple's implementation

### ISSUE THREAD

**Issue by epatey** [broadwaylamb/OpenCombine#47]
The common pattern in the unit tests is to assert that the string description of the entity that implements `Subscription` matches what Apple does. For example,
```Swift
// Testing .tryMap
 XCTAssertEqual(tracking.history, [.subscription("TryMap"),
```
or 
```Swift
// Testing .map
 XCTAssertEqual(tracking.history, [.subscription("PassthroughSubject"),
```

This seems strange to me. From my perspective, that's testing implementation details rather than behavior.

Notice how those two test cases above assert different subscription names. This is because Apple simply chose to proxy the subscription in the `TryMap` case, but not in the `Map` case. Of course, in our code, we do the same.

I would argue that this is an anti-pattern. In the `Map`/`TryMap` case, if we didn't need to match names of `Subscription` implementations, we wouldn't need to implement `Subscription` at all. It could simple be handled by the upstream publisher.

Are there benefits that I'm not understanding?

**Comment by broadwaylamb** [comment]
It all boils down to the question "what **is** an implementation detail and what is not".

In my opinion, whatever (even opaque) object the framework throws at us, we (as clients) should be able to query it for protocol conformances and rely on the result of those conformances (such as an object having certain string representation), unless it's explicitly discouraged in the documentation. And `CustomStringConvertible` is quite an important protocol. So is `CustomReflectable`. [SuperMirror'ing](https://github.com/broadwaylamb/SuperMirror) things, on the other hand, I consider relying on implementation details and it should not be tested.

Also, suppose a user finds a bug in OpenCombine or Combine and tries to debug it by extensively `print`ing or `dump`ing everything (like I do all the time). It would be super inconvenient if the names being printed differed depending on the framework.

In addition to that, I've been trying to stick as close to Apple's implementation as possible all along, and not only testing these details helps us make sure subscription history is right (how else would we be able to distinguish subscriptions?), but also sheds a light at how Combine is implemented.

I understand though, that we'll probably never be able to achieve the same quality of implementation as Combine, but we can still do our best to get closer to it.
