### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by gal-orlanczyk** [broadwaylamb/OpenCombine#48]
Hey guys! super cool initiative and amazing work!

I wanted to ask if you guys plan to add support for CocoaPods any time soon?

Thanks!

**Comment by broadwaylamb** [comment]
Hi!

I think that Swift Package Manager integrated into Xcode 11 should be enough for using OpenCombine in iOS/macOS/tvOS/watchOS projects, but if you feel like it's necessary, I can go ahead and add support for CocoaPods. Or you can help me out a bit and create a pull request :)

**Comment by reuvenlevitsky** [comment]
@broadwaylamb cocoapods would be amazing!

**Comment by raviTokopedia** [comment]
@broadwaylamb is anyone working on this? I'd like to pick this up.

**Comment by Ravi61** [comment]
@broadwaylamb is anyone working on this? I'd like to pick this up.

**Comment by broadwaylamb** [comment]
>@broadwaylamb is anyone working on this? I'd like to pick this up.

@Ravi61 feel free! That would be awesome.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by haemi** [comment]
is it possible to use SPM in an existing project with Cocoapods?

**Comment by broadwaylamb** [comment]
@haemi I don’t see any reason for it not to be possible, but I haven’t tried though.

**Comment by ohitsdaniel** [comment]
@gal-orlanczyk @reuvenlevitsky @Ravi61 @haemi 
CocoaPods is now supported 🥳
