### ISSUE TITLE
Supporting Foundation: why it is not possible to do it seamlessly

### ISSUE THREAD

**Issue by broadwaylamb** [broadwaylamb/OpenCombine#6]
So the newest version of Foundation **depends** on Apple's Combine and extends some types like `NotificationCenter` with convenience methods thet return Combine's `Publisher`s like this:

```swift
extension NotificationCenter {

    public func publisher(
        for name: Notification.Name,
        object: AnyObject? = nil
    ) -> NotificationCenter.Publisher {
        // ...
    }
}
```

So the problem is that if now OpenCombine declares the same extension, the clients which import both Foundation and OpenCombine won't be able to call such functions because of how the mechanism of extensions work:

```swift
let pub = NotificationCenter
    .default
    .publisher(for: NSControl.textDidChangeNotification,
               object: filterField)
 // error: ambiguous use of publisher(for:object:)
```

This is why OpenCombine cannot be fully compatible with Apple's Combine.

We can provide ways to handle this, but it's not perfect, of course:

- Function overloading — methods in extensions accept one additional argument that helps distinguish the overloads:
  
  ```swift
  public struct OpenCombineNotificationCenterPublisher: Publisher {
      // ...
  }

  public enum OpenCombineNamespace {
      case openCombine
  }
  
  extension NotificationCenter {

      public typealias Publisher = OpenCombineNotificationCenterPublisher
  
      public func publisher(
          for name: Notification.Name,
          object: AnyObject? = nil,
          _ namespace: OpenCombineNamespace
      ) -> OpenCombineNotificationCenterPublisher {
          // ...
      }
  }
  ```

  which then would be called like this:
  
  ```swift
  let pub = NotificationCenter
      .default
      .publisher(for: NSControl.textDidChangeNotification,
                 object: filterField,
                 .openCombine)
  ```
  
  This is what, for example, [PromiseKit](https://github.com/mxcl/PromiseKit) does, but there's one pitfall: it doesn't work with properties.

- Newtype exposed via property:

  ```swift
  public struct OpenCombineNotificationCenter {
      public let underlying: NotificationCenter

      public func publisher(
          for name: Notification.Name,
          object: AnyObject? = nil
      ) -> Publisher {
         // ...
      }
      
      public struct Publisher: OpenCombine.Publisher {
          // ...
      }
  }
  
  extension NotificationCenter {
      var openCombine: OpenCombineNotificationCenter {
          return OpenCombineNotificationCenter(underlying: self)
      }
  }
  ```
  
  At call site it looks like this:
  
  ```swift
   let pub = NotificationCenter
      .default
      .openCombine
      .publisher(for: NSControl.textDidChangeNotification,
                 object: filterField,
                 .openCombine)
  ```

I'd personally took the second approach, but until we implement the fundamental functionality of Apple's Combine there's time to think on this.

**Comment by viktorasl** [comment]
There is another solution that resolves ambiguity:
```swift
let pub: OpenCombine.Publisher = NotificationCenter
    .default
    .publisher(for: NSControl.textDidChangeNotification,
               object: filterField)
```

**Comment by viktorasl** [comment]
Another way, which is not that appealing and would require lots of duplication is to replicate `NotificationCenter` in `OpenCombine` framework:
```swift
class NotificationCenter {
    public func publisher(
        for name: Notification.Name,
        object: AnyObject? = nil
    ) -> NotificationCenter.Publisher {
        // ...
    }
}
```
at call site it would look like:
```swift
import OpenCombine

let pub = OpenCombine.NotificationCenter
    .default
    .publisher(for: NSControl.textDidChangeNotification,
               object: filterField)
```

EDIT:

Nope, it won't work that easily, it requires `default` static var and might be even more...

**Comment by rahul0x24** [comment]
One way to remove ambiguity can be by using a proxy pattern. 
```swift
public protocol OpenCombineExtensionsProvider {}
extension OpenCombineExtensionsProvider {
	public var oc: OpenCombine <Self> {
		return OpenCombine(self)
	}
}

public struct OpenCombine<Base> {
	public let base: Base
	fileprivate init(_ base: Base) {
		self.base = base
	}
}
```
```swift
extension OpenCombine where Base: NotificationCenter {
    public func publisher(
        for name: Notification.Name,
        object: AnyObject? = nil
    ) -> NotificationCenter.Publisher {
        // ...
    }
}
```
The you can call the same methods with namespace 'oc'.
```swift
let pub = NotificationCenter.default.oc.publisher(
	for: NSControl.textDidChangeNotification, object: filterField
)
```

Refer: https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Reactive.swift

**Comment by broadwaylamb** [comment]
@RahulKatariya the looks even better and more concise, thank you!

What I’m thinking about is to do this namespacing thing on Apple platforms, but on non-Apple platforms (Linux, Windows) also add extensions to the original types, since no Combine is present there, hence no ambiguity.

**Comment by rahul0x24** [comment]
@broadwaylamb Adding extensions to original types for windows and linux would not give much benefit, just an extra maintenance and synchronization.

Most of the people using OpenCombine in a Swift Package will be supporting all the platforms - Apple, Linux and Window and will make use of one API. What I mean is, I don't think anyone would have the following checks in their code.

```swift
#if !os(Apple)
let pub = NotificationCenter.default.publisher( 
	for: NSControl.textDidChangeNotification, object: filterField
)
#else
let pub = NotificationCenter.default.oc.publisher(
	for: NSControl.textDidChangeNotification, object: filterField
)
#endif
``` 

I am not sure about this part, If you are having any other use case in mind.

**Comment by broadwaylamb** [comment]
@RahulKatariya no, as a client you won't have to perform these checks.

I'm talking about this:

```swift
extension NotificationCenter {

    public var openCombine: OpenCombine<NotificationCenter> {
        return OpenCombine(self)
    }

#if !canImport(Combine)
    public func publisher(
        for name: Notification.Name,
        object: AnyObject? = nil
    ) -> NotificationCenter.Publisher {
        return self.openCombine
            .publisher(for: name, object: object)
    }
#endif
}
```

As a client who targets Linux and, say, macOS prior to 10.15, you will always use:
```swift
let pub = NotificationCenter.default.openCombine.publisher(
    for: NSControl.textDidChangeNotification, object: filterField
)
```

If you target Linux and macOS 10.15 (or newer), since you don't have to link against OpenCombine on macOS, you will use:
```swift
let pub = NotificationCenter.default.publisher(
    for: NSControl.textDidChangeNotification, object: filterField
)
```

**Comment by rahul0x24** [comment]
@broadwaylamb - This looks great 😎.
