### ISSUE TITLE
Extra call to sink

### ISSUE THREAD

**Issue by abeazam** [broadwaylamb/OpenCombine#68]
I wrote a little example the I tested in Combine and Open Combine and got two different outputs.

`_ = Publishers.Sequence(sequence: [1,2,3,4,5,6])
        .map {
            print("map:" , $0);
            return  String($0)
        }
        .sink(receiveValue: {
            print("sink: " , $0)
        })`

Expected output based on Combine import:

map: 1
map: 2
map: 3
map: 4
map: 5
map: 6
sink:  1
sink:  2
sink:  3
sink:  4
sink:  5
sink:  6

Actual output base on OpenCombine output 0.3.0:
map: 1
map: 2
map: 3
map: 4
map: 5
map: 6
sink:  2 <- this is the offending print 
sink:  1
sink:  2
sink:  3
sink:  4
sink:  5
sink:  6

**Comment by broadwaylamb** [comment]
Thank you! I’ll fix it right away

**Comment by broadwaylamb** [comment]
Looks like this has already been fixed in the master branch by #62. Can you please verify your test case against the master branch?

**Comment by abeazam** [comment]
tested and RESOLVED!!!!!! great thanks
